using System.Text.Json.Serialization;

namespace Rake.Core.Models;

public record Entry(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("title")] string Title,
    [property: JsonPropertyName("creator")] string Creator,
    [property: JsonPropertyName("duration")] int Duration,
    [property: JsonPropertyName("timestamp")] int Timestamp,
    [property: JsonPropertyName("release_timestamp")] int ReleaseTimestamp,
    [property: JsonPropertyName("description")] string Description,
    [property: JsonPropertyName("view_count")] int ViewCount,
    [property: JsonPropertyName("like_count")] int LikeCount,
    [property: JsonPropertyName("tags")] IReadOnlyList<string> Tags,
    [property: JsonPropertyName("dislike_count")] int DislikeCount,
    [property: JsonPropertyName("thumbnail")] string Thumbnail,
    [property: JsonPropertyName("series")] string Series,
    [property: JsonPropertyName("formats")] IReadOnlyList<Format> Formats,
    [property: JsonPropertyName("ext")] string Ext,
    [property: JsonPropertyName("playlist_count")] int PlaylistCount,
    [property: JsonPropertyName("playlist")] string Playlist,
    [property: JsonPropertyName("playlist_id")] object PlaylistId,
    [property: JsonPropertyName("playlist_title")] string PlaylistTitle,
    [property: JsonPropertyName("playlist_uploader")] object PlaylistUploader,
    [property: JsonPropertyName("playlist_uploader_id")] object PlaylistUploaderId,
    [property: JsonPropertyName("playlist_channel")] object PlaylistChannel,
    [property: JsonPropertyName("playlist_channel_id")] object PlaylistChannelId,
    [property: JsonPropertyName("n_entries")] int NEntries,
    [property: JsonPropertyName("webpage_url")] string WebpageUrl,
    [property: JsonPropertyName("webpage_url_basename")] string WebpageUrlBasename,
    [property: JsonPropertyName("webpage_url_domain")] string WebpageUrlDomain,
    [property: JsonPropertyName("playlist_index")] int PlaylistIndex,
    [property: JsonPropertyName("__last_playlist_index")] int LastPlaylistIndex,
    [property: JsonPropertyName("extractor")] string Extractor,
    [property: JsonPropertyName("extractor_key")] string ExtractorKey,
    [property: JsonPropertyName("playlist_autonumber")] int PlaylistAutonumber,
    [property: JsonPropertyName("thumbnails")] IReadOnlyList<Thumbnail> Thumbnails,
    [property: JsonPropertyName("display_id")] string DisplayId,
    [property: JsonPropertyName("fulltitle")] string Fulltitle,
    [property: JsonPropertyName("duration_string")] string DurationString,
    [property: JsonPropertyName("upload_date")] string UploadDate,
    [property: JsonPropertyName("release_date")] string ReleaseDate,
    [property: JsonPropertyName("release_year")] int ReleaseYear,
    [property: JsonPropertyName("creators")] IReadOnlyList<string> Creators,
    [property: JsonPropertyName("requested_subtitles")] object RequestedSubtitles,
    [property: JsonPropertyName("_has_drm")] object HasDrm,
    [property: JsonPropertyName("epoch")] int Epoch,
    [property: JsonPropertyName("requested_downloads")]
        IReadOnlyList<RequestedDownload> RequestedDownloads,
    [property: JsonPropertyName("url")] string Url,
    [property: JsonPropertyName("format_id")] string FormatId,
    [property: JsonPropertyName("width")] int Width,
    [property: JsonPropertyName("height")] int Height,
    [property: JsonPropertyName("filesize_approx")] int FilesizeApprox,
    [property: JsonPropertyName("protocol")] string Protocol,
    [property: JsonPropertyName("resolution")] string Resolution,
    [property: JsonPropertyName("dynamic_range")] string DynamicRange,
    [property: JsonPropertyName("aspect_ratio")] double AspectRatio,
    [property: JsonPropertyName("http_headers")] HttpHeaders HttpHeaders,
    [property: JsonPropertyName("video_ext")] string VideoExt,
    [property: JsonPropertyName("audio_ext")] string AudioExt,
    [property: JsonPropertyName("vbr")] object Vbr,
    [property: JsonPropertyName("abr")] object Abr,
    [property: JsonPropertyName("tbr")] object Tbr,
    [property: JsonPropertyName("format")] string Format
);
