using System.Text.Json.Serialization;

namespace Rake.Core.Models;

public record Video(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("title")] string Title,
    [property: JsonPropertyName("duration")] int Duration,
    [property: JsonPropertyName("thumbnails")] IReadOnlyList<Thumbnail> Thumbnails,
    [property: JsonPropertyName("uploader")] string Uploader,
    [property: JsonPropertyName("uploader_id")] string UploaderId,
    [property: JsonPropertyName("timestamp")] int Timestamp,
    [property: JsonPropertyName("view_count")] int ViewCount,
    [property: JsonPropertyName("chapters")] IReadOnlyList<Chapter> Chapters,
    [property: JsonPropertyName("is_live")] bool IsLive,
    [property: JsonPropertyName("was_live")] bool WasLive,
    [property: JsonPropertyName("formats")] IReadOnlyList<Format> Formats,
    [property: JsonPropertyName("subtitles")] Subtitles Subtitles,
    [property: JsonPropertyName("webpage_url")] string WebpageUrl,
    [property: JsonPropertyName("webpage_url_basename")] string WebpageUrlBasename,
    [property: JsonPropertyName("webpage_url_domain")] string WebpageUrlDomain,
    [property: JsonPropertyName("extractor")] string Extractor,
    [property: JsonPropertyName("extractor_key")] string ExtractorKey,
    [property: JsonPropertyName("thumbnail")] string Thumbnail,
    [property: JsonPropertyName("display_id")] string DisplayId,
    [property: JsonPropertyName("fulltitle")] string FullTitle,
    [property: JsonPropertyName("duration_string")] string DurationString,
    [property: JsonPropertyName("upload_date")] string UploadDate,
    [property: JsonPropertyName("live_status")] string LiveStatus,
    [property: JsonPropertyName("epoch")] int Epoch,
    [property: JsonPropertyName("format_id")] string FormatId,
    [property: JsonPropertyName("url")] string Url,
    [property: JsonPropertyName("manifest_url")] string ManifestUrl,
    [property: JsonPropertyName("tbr")] double Tbr,
    [property: JsonPropertyName("ext")] string Ext,
    [property: JsonPropertyName("fps")] int Fps,
    [property: JsonPropertyName("protocol")] string Protocol,
    [property: JsonPropertyName("has_drm")] bool HasDrm,
    [property: JsonPropertyName("width")] int Width,
    [property: JsonPropertyName("height")] int Height,
    [property: JsonPropertyName("vcodec")] string VCodec,
    [property: JsonPropertyName("acodec")] string ACodec,
    [property: JsonPropertyName("dynamic_range")] string DynamicRange,
    [property: JsonPropertyName("resolution")] string Resolution,
    [property: JsonPropertyName("aspect_ratio")] double AspectRatio,
    [property: JsonPropertyName("http_headers")] HttpHeaders HttpHeaders,
    [property: JsonPropertyName("video_ext")] string VideoExt,
    [property: JsonPropertyName("audio_ext")] string AudioExt,
    [property: JsonPropertyName("format")] string Format,
    [property: JsonPropertyName("_type")] string Type,
    [property: JsonPropertyName("_version")] Version Version
);
