using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using H.Generators.Extensions;
using Microsoft.CodeAnalysis.Diagnostics;
using Rake.Generators.Abstractions;
using Rake.Generators.Attributes;
using Rake.Generators.Extensions;
using Rake.Generators.Utilities;

namespace Rake.Generators;

// [Generator]
internal sealed class ConstructorGenerator : GeneratorForMember<ClassDeclarationSyntax>
{
    protected override string Id => "CG";

    protected override IEnumerable<FileWithName> StaticSources { get; } =
        [
            new FileWithName(
                $"{Meta.Namespace}.Activation",
                $$"""

                #nullable enable

                using System.ComponentModel;
                using System.Windows;

                namespace {{Meta.Namespace}};

                public interface IActivatable
                {
                    public void Activate();
                    
                    public void Deactivate();
                }

                public static class Activation
                {
                    public static void Register(this INotifyPropertyChanged viewModel, FrameworkElement frameworkElement)
                    {
                        var activatableViewModel = viewModel as IActivatable;
                        var activatableView = frameworkElement as IActivatable;
                        if (activatableViewModel == null && activatableView == null)
                        {
                            return;
                        }

                        frameworkElement =
                            frameworkElement ?? throw new ArgumentNullException(nameof(frameworkElement));

                        frameworkElement.Loaded += Loaded;
                        frameworkElement.Unloaded += Unloaded;
                        return;

                        void Loaded(object? sender, RoutedEventArgs e)
                        {
                            activatableViewModel?.Activate();
                            activatableView?.Activate();
                        }
                        void Unloaded(object? sender, RoutedEventArgs e)
                        {
                            activatableViewModel?.Deactivate();
                            activatableView?.Deactivate();

                            frameworkElement.Loaded -= Loaded;
                            frameworkElement.Unloaded -= Unloaded;
                        }
                    }
                }
                """.AddAutoGeneratedMessage()
            )
        ];

    protected override bool IsSyntaxTarget(SyntaxNode node, CancellationToken ct)
    {
        if (node is BaseTypeDeclarationSyntax baseTypeDeclarationSyntax)
        {
            return baseTypeDeclarationSyntax.Identifier.Text.EndsWith("ViewModel");
        }

        return false;
    }

    protected override IEnumerable<FileWithName> GenerateCodes(
        ImmutableArray<ClassDeclarationSyntax> nodes,
        AnalyzerConfigOptions options
    )
    {
        var targetSymbol = Compilation.GetTypeByMetadataName(Meta.ObservableObject);

        var viewModelSymbols = GetAll<INamedTypeSymbol>(nodes)
            .Where(x => !x.IsAbstract)
            .Where(x => !x.HasAttribute<IgnoreAttribute>())
            .Where(x => x.Name.EndsWith("ViewModel"))
            .Where(x => x.IsOfBaseType(targetSymbol))
            .OrderBy(x => x.ToDisplayString())
            .ToArray();

        foreach (var viewModelSymbol in viewModelSymbols)
        {
            var viewSymbol = GetView(viewModelSymbol);
            if (viewSymbol is null)
                continue;

            var source = new SourceStringBuilder(viewSymbol);

            source.Line("using Rake.Generators;");
            source.Line();
            source.PartialTypeBlockBrace(() =>
            {
                source.Line("partial void BeforeInitializeComponent();");
                source.Line("partial void AfterInitializeComponent();");
                source.Line();
                source.Constructor(
                    $"{viewModelSymbol.ToFullDisplayString()} viewModel",
                    () =>
                    {
                        source.Line("ViewModel = viewModel;");
                        source.Line();
                        source.Line("BeforeInitializeComponent();");
                        source.Line("InitializeComponent();");
                        source.Line("AfterInitializeComponent();");
                        source.Line();
                        source.Line("viewModel.Register(this);");
                    }
                );
            });

            yield return new FileWithName(
                $"{viewSymbol.ToDisplayString()}.Constructor.g.cs",
                source.ToString()
            );
        }
    }

    private INamedTypeSymbol? GetView(ISymbol symbol)
    {
        var viewName = symbol.ToDisplayString().Replace("ViewModel", "View");
        var viewSymbol = Compilation.GetTypeByMetadataName(viewName);

        if (viewSymbol is not null)
            return viewSymbol;

        viewName = symbol.ToDisplayString().Replace(".ViewModels.", ".Views.");
        viewName = viewName.Remove(viewName.IndexOf("ViewModel", StringComparison.Ordinal));
        return Compilation.GetTypeByMetadataName(viewName);
    }
}
