using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Threading;
using H.Generators.Extensions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Diagnostics;
using Rake.Generators.Abstractions;
using Rake.Generators.Attributes;
using Rake.Generators.Extensions;
using Rake.Generators.Utilities;

namespace Rake.Generators;

[Generator]
internal sealed class DependencyInjectionGenerator : GeneratorForMember<ClassDeclarationSyntax>
{
    protected override string Id => "DIG";

    protected override IEnumerable<FileWithName> StaticSources { get; } =
        [
            new FileWithName(
                $"{Meta.DependencyInjectionNamespace}.d",
                $$"""
                using Microsoft.Extensions.DependencyInjection;

                namespace {{Meta.DependencyInjectionNamespace}}
                {
                    public static partial class ServiceCollectionExtensions
                    {
                        static partial void AddViewsAndViewModels(IServiceCollection services);
                    
                        public static IServiceCollection AddCore(this IServiceCollection services)
                        {
                            AddViewsAndViewModels(services);
                            return services;
                        }
                    }
                }
                """.AddAutoGeneratedMessage()
            )
        ];

    protected override bool IsSyntaxTarget(SyntaxNode node, CancellationToken ct)
    {
        ct.ThrowIfCancellationRequested();
        if (node is ClassDeclarationSyntax baseTypeDeclarationSyntax)
        {
            return baseTypeDeclarationSyntax.Identifier.Text.EndsWith("ViewModel");
        }

        return false;
    }

    protected override FileWithName GenerateCode(
        ImmutableArray<ClassDeclarationSyntax> nodes,
        AnalyzerConfigOptions options
    )
    {
        var targetSymbol = Compilation.GetTypeByMetadataName(Meta.ObservableObject);

        var viewModelSymbols = GetAll<INamedTypeSymbol>(nodes)
            .Where(x => !x.IsAbstract)
            .Where(x => !x.HasAttribute<IgnoreAttribute>())
            .Where(x => x.Name.EndsWith("ViewModel"))
            .Where(x => x.IsOfBaseType(targetSymbol))
            .OrderBy(x => x.ToDisplayString())
            .ToArray();

        var source = new SourceStringBuilder();

        source.Line();
        source.Line("using Microsoft.Extensions.DependencyInjection;");
        source.Line();

        source.NamespaceBlockBrace(
            $"{Meta.DependencyInjectionNamespace}",
            () =>
            {
                source.Line("public static partial class ServiceCollectionExtensions");
                source.BlockBrace(() =>
                {
                    source.Line(
                        "static partial void AddViewsAndViewModels(IServiceCollection services)"
                    );
                    source.BlockBrace(() =>
                    {
                        var count = 0;
                        foreach (var viewModelSymbol in viewModelSymbols)
                        {
                            var viewSymbol = GetView(viewModelSymbol);

                            if (viewSymbol is null)
                                continue;

                            source.Line(
                                viewModelSymbol.HasAttribute<SingletonAttribute>()
                                    ? $"services.AddSingleton<{viewModelSymbol.ToFullDisplayString()}>();"
                                    : $"services.AddTransient<{viewModelSymbol.ToFullDisplayString()}>();"
                            );
                            if (viewModelSymbol.BaseType is { } viewModelBaseTypeSymbol)
                            {
                                source.Line(
                                    viewModelSymbol.HasAttribute<SingletonAttribute>()
                                        ? $"services.AddSingleton<{viewModelBaseTypeSymbol.ToFullDisplayString()}>(sp => sp.GetRequiredService<{viewModelSymbol.ToFullDisplayString()}>());"
                                        : $"services.AddTransient<{viewModelBaseTypeSymbol.ToFullDisplayString()}>(sp => sp.GetRequiredService<{viewModelSymbol.ToFullDisplayString()}>());"
                                );
                            }

                            source.Line(
                                $"services.AddTransient(sp => new {viewSymbol.ToFullDisplayString()}(sp.GetRequiredService<{viewModelSymbol.ToFullDisplayString()}>()));"
                            );

                            if (++count != viewModelSymbols.Length)
                            {
                                source.Line();
                            }
                        }
                    });
                });
            }
        );

        return new FileWithName($"{Meta.DependencyInjectionNamespace}.i.g.cs", source.ToString());
    }

    private INamedTypeSymbol? GetView(ISymbol viewModelSymbol)
    {
        var viewName = viewModelSymbol.ToDisplayString().Replace("ViewModel", "View");
        var viewSymbol = Compilation.GetTypeByMetadataName(viewName);

        if (viewSymbol is not null)
            return viewSymbol;

        viewName = viewModelSymbol.ToDisplayString().Replace(".ViewModels.", ".Views.");
        viewName = viewName.Remove(viewName.IndexOf("ViewModel", StringComparison.Ordinal));
        return Compilation.GetTypeByMetadataName(viewName);
    }
}
