using System.Collections.Generic;
using System.Linq;
using System.Threading;
using H.Generators.Extensions;
using Microsoft.CodeAnalysis.Diagnostics;
using Rake.Generators.Abstractions;
using Rake.Generators.Attributes;
using Rake.Generators.Extensions;
using Rake.Generators.Utilities;

namespace Rake.Generators;

[Generator]
internal sealed class DependencyInjectionGenerator : GeneratorForMember<ClassDeclarationSyntax>
{
    protected override string Id => "DIG";

    protected override IEnumerable<FileWithName> StaticSources { get; } =
        [
            new FileWithName(
                $"{Meta.DependencyInjectionNamespace}.d",
                $$"""
                using Microsoft.Extensions.DependencyInjection;

                namespace {{Meta.DependencyInjectionNamespace}}
                {
                    public static partial class ServiceCollectionExtensions
                    {
                        static partial void AddViewModels(IServiceCollection services);
                    
                        public static IServiceCollection AddGenerated(this IServiceCollection services)
                        {
                            AddViewModels(services);
                            return services;
                        }
                    }
                }
                """.AddAutoGeneratedMessage()
            )
        ];

    protected override bool IsSyntaxTarget(SyntaxNode node, CancellationToken ct)
    {
        ct.ThrowIfCancellationRequested();
        if (node is ClassDeclarationSyntax baseTypeDeclarationSyntax)
        {
            return baseTypeDeclarationSyntax.Identifier.Text.EndsWith("ViewModel");
        }

        return false;
    }

    protected override FileWithName GenerateCode(
        ImmutableArray<ClassDeclarationSyntax> nodes,
        AnalyzerConfigOptions options
    )
    {
        var targetSymbol = Compilation.GetTypeByMetadataName(Meta.ObservableObject);

        var viewModels = GetAll<INamedTypeSymbol>(nodes)
            .Where(x => !x.IsAbstract)
            .Where(x => !x.HasAttribute<IgnoreAttribute>())
            .Where(x => x.Name.EndsWith("ViewModel"))
            .Where(x => x.IsOfBaseType(targetSymbol))
            .OrderBy(x => x.ToDisplayString())
            .ToArray();

        var source = new SourceStringBuilder();

        source.Line();
        source.Line("using Microsoft.Extensions.DependencyInjection;");
        source.Line();

        source.NamespaceBlockBrace(
            $"{Meta.DependencyInjectionNamespace}",
            () =>
            {
                source.Line("public static partial class ServiceCollectionExtensions");
                source.BlockBrace(() =>
                {
                    source.Line("static partial void AddViewModels(IServiceCollection services)");
                    source.BlockBrace(() =>
                    {
                        foreach (var viewModel in viewModels)
                        {
                            source.Line(
                                viewModel.HasAttribute<SingletonAttribute>()
                                    ? $"services.AddSingleton<{viewModel.ToFullDisplayString()}>();"
                                    : $"services.AddTransient<{viewModel.ToFullDisplayString()}>();"
                            );

                            if (viewModel.BaseType is not { } viewModelBaseType)
                                continue;

                            source.Line(
                                viewModel.HasAttribute<SingletonAttribute>()
                                    ? $"services.AddSingleton<{viewModelBaseType.ToFullDisplayString()}>(sp => sp.GetRequiredService<{viewModel.ToFullDisplayString()}>());"
                                    : $"services.AddTransient<{viewModelBaseType.ToFullDisplayString()}>(sp => sp.GetRequiredService<{viewModel.ToFullDisplayString()}>());"
                            );
                        }
                    });
                });
            }
        );

        return new FileWithName($"{Meta.DependencyInjectionNamespace}.i.g.cs", source.ToString());
    }
}
