using System;
using System.Collections.Generic;
using System.Linq;
using H;
using H.Generators.Extensions;
using Microsoft.CodeAnalysis.Diagnostics;
using Rake.Generators.Abstractions;
using Rake.Generators.Attributes;
using Rake.Generators.Extensions;
using Rake.Generators.Utilities;

namespace Rake.Generators;

[Generator]
internal sealed class StaticViewLocatorGenerator
    : GeneratorForTypeWithAttribute<StaticViewLocatorAttribute>
{
    protected override string Id => "SVLG";

    protected override IEnumerable<FileWithName> StaticSources =>
        [
            new FileWithName(
                $"{typeof(StaticViewLocatorAttribute).FullName}",
                Resources.StaticViewLocatorAttribute_cs.AsString().AddAutoGeneratedMessage()
            ),
            new FileWithName(
                $"{typeof(SingletonAttribute).FullName}",
                Resources.SingletonAttribute_cs.AsString().AddAutoGeneratedMessage()
            ),
            new FileWithName(
                $"{typeof(IgnoreAttribute).FullName}",
                Resources.IgnoreAttribute_cs.AsString().AddAutoGeneratedMessage()
            ),
        ];

    protected override string GenerateCode(
        SyntaxNode node,
        INamedTypeSymbol symbol,
        AttributeData attribute,
        AnalyzerConfigOptions options
    )
    {
        var targetSymbol = Compilation.GetTypeByMetadataName(Meta.ObservableObject);

        var viewModelSymbols = Compilation
            .GlobalNamespace.CollectTypeSymbols(targetSymbol)
            .Where(x => !x.IsAbstract)
            .Where(x => !x.HasAttribute<IgnoreAttribute>())
            .OrderBy(x => x.ToDisplayString());

        var source = new SourceStringBuilder(symbol);

        source.Line();
        source.Line("using System;");
        source.Line("using System.Collections.Generic;");
        source.Line("using Avalonia.Controls;");
        source.Line("using Avalonia.Controls.Templates;");
        source.Line();

        source.PartialTypeBlockBrace(
            "IDataTemplate",
            () =>
            {
                source.Line(
                    "public static Dictionary<Type, Func<object, Control>> ViewMap { get; } = new()"
                );
                source.BlockDecl(() =>
                {
                    foreach (var viewModelSymbol in viewModelSymbols)
                    {
                        var view = GetView(viewModelSymbol);

                        if (view is null)
                            continue;

                        source.Line(
                            $"[typeof({viewModelSymbol.ToFullDisplayString()})] = (viewModel) => new {view.ToFullDisplayString()}() {{ ViewModel = ({viewModelSymbol.ToFullDisplayString()})viewModel }},"
                        );
                    }
                });
            }
        );

        return source.ToString();
    }

    private INamedTypeSymbol? GetView(ISymbol symbol)
    {
        var viewName = symbol.ToDisplayString().Replace("ViewModel", "View");
        var viewSymbol = Compilation.GetTypeByMetadataName(viewName);

        if (viewSymbol is not null)
            return viewSymbol;

        viewName = symbol.ToDisplayString().Replace(".ViewModels.", ".Views.");
        viewName = viewName.Remove(viewName.IndexOf("ViewModel", StringComparison.Ordinal));
        return Compilation.GetTypeByMetadataName(viewName);
    }
}
