using IDeepCloneable.Generator;
using Microsoft.CodeAnalysis;

namespace Rake.Configuration.Writable.Generator;

// Generator
[Generator]
internal class CloneableGenerator : CloneableGeneratorCore<GeneratorOptions>;

// Options
internal class GeneratorOptions : CloneableGeneratorOptionsCore
{
    // The DeepClone implementation will be generated for types with this attribute.
    public override string AttributeMetadataName => "Rake.Configuration.Writable.OptionsAttribute";

    // Specify the interface name that generated types should implement. If empty, only a partial class is generated.
    public override string ImplementedInterfaceName =>
        "global::Rake.Configuration.Writable.Abstractions.IDeepCloneable";

    public override string ExtensionsNamespace => "Rake.Configuration.Writable";

    public override string GeneratedHeaderComment =>
        "This file is generated by Rake.Configuration.Writable.Generator";
}
