namespace Rake.Generators.Utilities;

internal static class Meta
{
    public const string TopMessage = """
        //------------------------------------------------------------------------------
        // <auto-generated>
        //     This code was generated.
        //
        //     Changes to this file may cause incorrect behavior and will be lost if
        //     the code is regenerated.
        // </auto-generated>
        //------------------------------------------------------------------------------
        """;

    public const string BottomMessage = """
        //------------------------------------------------------------------------------
        // <auto-generated>
        //     Roslyn doesn't clear the file when writing debug output for
        //     EmitCompilerGeneratedFiles, so I'm writing this message to
        //     make it more obvious what's going on when that happens.
        // </auto-generated>
        //------------------------------------------------------------------------------
        """;
    public const string AppName = "Rake.Generators";
    public const string Namespace = $"{AppName}";
    public const string DependencyInjectionNamespace = $"{Namespace}.DependencyInjection";
    public const string Attributes = $"{AppName}.{nameof(Attributes)}";
    public const string Interfaces = $"{AppName}.{nameof(Interfaces)}";
    public const string Control = "Avalonia.Controls.Control";
    public const string Window = "Avalonia.Controls.Window";
    public const string UserControl = "Avalonia.Controls.UserControl";
    public const string ObservableObject = "CommunityToolkit.Mvvm.ComponentModel.ObservableObject";
    public const string NotifyPropertyChanged = "System.ComponentModel.INotifyPropertyChanged";
}
