using System.Text.RegularExpressions;
using Microsoft.CodeAnalysis;
using Rake.SourceGenerators.Core.Internals;

namespace Rake.SourceGenerators.Core;

public sealed class CodeBuilder
{
    private const string DefaultAutoGeneratedMessage =
        @"This code was generated.

Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.";

    // Static compiled Regex for netstandard2.0 performance
    private static readonly Regex UsingPrefixRegex = new(@"^using\s+", RegexOptions.Compiled);
    private static readonly Regex NewlineRegex = new(@"\r\n|\r|\n", RegexOptions.Compiled);

    private string? _autoGeneratedMessage;
    private readonly HashSet<string> _namespaceImports = new(StringComparer.Ordinal);
    private readonly List<string> _assemblyAttributes = [];
    private readonly List<IBuilder> _builders = [];
    private bool _topLevel;
    private NullableState _nullable = NullableState.Default;

    private CodeBuilder(string? clrNamespace = null, IndentStyle indentStyle = IndentStyle.Spaces)
    {
        Namespace = clrNamespace;
        IndentStyle = indentStyle;
    }

    public string? Namespace { get; }

    public IndentStyle IndentStyle { get; }

    public IReadOnlyList<ClassBuilder> Classes => _builders.OfType<ClassBuilder>().ToList();

    public IReadOnlyList<RecordBuilder> Records => _builders.OfType<RecordBuilder>().ToList();

    public IReadOnlyList<EnumBuilder> Enums => _builders.OfType<EnumBuilder>().ToList();

    public IReadOnlyList<DelegateBuilder> Delegates => _builders.OfType<DelegateBuilder>().ToList();

    public CodeBuilder TopLevelNamespace() => TopLevelNamespace(true);

    public CodeBuilder TopLevelNamespace(bool topLevel)
    {
        _topLevel = topLevel;
        return this;
    }

    public CodeBuilder Nullable() => Nullable(NullableState.Enable);

    public CodeBuilder Nullable(NullableState nullable)
    {
        _nullable = nullable;
        return this;
    }

    public static CodeBuilder CreateInGlobalNamespace(
        IndentStyle indentStyle = IndentStyle.Spaces
    ) => new CodeBuilder(indentStyle: indentStyle).TopLevelNamespace();

    public static CodeBuilder Create(
        string clrNamespace,
        IndentStyle indentStyle = IndentStyle.Spaces
    ) => new(clrNamespace, indentStyle);

    public static CodeBuilder Create(
        INamespaceSymbol namespaceSymbol,
        IndentStyle indentStyle = IndentStyle.Spaces
    ) => Create(namespaceSymbol.ToDisplayString(), indentStyle);

    public static ClassBuilder Create(
        ITypeSymbol typeSymbol,
        IndentStyle indentStyle = IndentStyle.Spaces
    )
    {
        var builder = Create(typeSymbol.ContainingNamespace, indentStyle);
        return builder
            .AddClass(typeSymbol.Name)
            .WithAccessModifier(typeSymbol.DeclaredAccessibility)
            .OfType(typeSymbol.TypeKind);
    }

    public CodeBuilder AddNamespaceImport(string importedNamespace)
    {
        if (string.IsNullOrWhiteSpace(importedNamespace))
            return this;

        var value = UsingPrefixRegex
            .Replace(importedNamespace, string.Empty)
            .Replace(";", string.Empty)
            .Trim();

        if (value.Length > 0)
            _namespaceImports.Add(value);

        return this;
    }

    public CodeBuilder AddNamespaceImport(ISymbol symbol)
    {
        if (symbol.ContainingNamespace is { } ns)
            return AddNamespaceImport(ns.ToDisplayString());

        return this;
    }

    public CodeBuilder AddNamespaceImport(INamespaceSymbol symbol)
    {
        return AddNamespaceImport(symbol.ToDisplayString());
    }

    public CodeBuilder AddAssemblyAttribute(string attribute)
    {
        if (!string.IsNullOrWhiteSpace(attribute))
            _assemblyAttributes.Add(attribute);

        return this;
    }

    public ClassBuilder AddClass(string name)
    {
        var builder = new ClassBuilder(name, this);
        _builders.Add(builder);
        return builder;
    }

    public ClassBuilder AddClass(ITypeSymbol symbol) => AddClass(symbol.Name);

    internal ClassBuilder AddClass(ClassBuilder builder)
    {
        _builders.Add(builder);
        builder.Builder = this;
        return builder;
    }

    public RecordBuilder AddRecord(string name)
    {
        var builder = new RecordBuilder(name, this);
        _builders.Add(builder);
        return builder;
    }

    internal RecordBuilder AddRecord(RecordBuilder builder)
    {
        _builders.Add(builder);
        builder.Builder = this;
        return builder;
    }

    public EnumBuilder AddEnum(string name)
    {
        var builder = new EnumBuilder(name, this);
        _builders.Add(builder);
        return builder;
    }

    internal EnumBuilder AddEnum(EnumBuilder builder)
    {
        _builders.Add(builder);
        builder.Builder = this;
        return builder;
    }

    public DelegateBuilder AddDelegate(string name)
    {
        var builder = new DelegateBuilder(name, this);
        _builders.Add(builder);
        return builder;
    }

    public CodeBuilder WithAutoGeneratedMessage(string message)
    {
        _autoGeneratedMessage = message;
        return this;
    }

    public void Clear()
    {
        _namespaceImports.Clear();
        _assemblyAttributes.Clear();
        _builders.Clear();
    }

    private CodeWriter BuildInternal()
    {
        var writer = new CodeWriter(IndentStyle);
        writer.AppendLine(
            "//------------------------------------------------------------------------------"
        );
        writer.AppendLine("// <auto-generated>");

        var autoGeneratedMessage = string.IsNullOrEmpty(_autoGeneratedMessage)
            ? DefaultAutoGeneratedMessage
            : _autoGeneratedMessage;

        var lines = NewlineRegex.Split(autoGeneratedMessage!);
        foreach (var line in lines)
        {
            writer.AppendLine($"//     {line.Trim()}");
        }

        writer.AppendLine("// </auto-generated>");
        writer.AppendLine(
            "//------------------------------------------------------------------------------"
        );
        writer.NewLine();

        if (_namespaceImports.Count > 0)
        {
            var systemImports = new List<string>();
            var standardImports = new List<string>();
            var aliasImports = new List<string>();

            foreach (var import in _namespaceImports)
            {
                if (import.Contains("="))
                    aliasImports.Add(import);
                else if (import.StartsWith("System", StringComparison.Ordinal))
                    systemImports.Add(import);
                else
                    standardImports.Add(import);
            }

            systemImports.Sort(StringComparer.Ordinal);
            standardImports.Sort(StringComparer.Ordinal);
            aliasImports.Sort(StringComparer.Ordinal);

            WriteNamespaceGroup(systemImports, ref writer);
            WriteNamespaceGroup(standardImports, ref writer);
            WriteNamespaceGroup(aliasImports, ref writer);

            writer.NewLine();
        }

        if (_nullable != NullableState.Default)
            writer.AppendLine($"#nullable {_nullable.ToString().ToLowerInvariant()}");

        WriteAssemblyAttributes(_assemblyAttributes, ref writer);

        if (_topLevel)
        {
            if (Namespace is not null)
            {
                writer.AppendLine($"namespace {Namespace};");
                writer.NewLine();
            }

            WriteBody(writer);
            return writer;
        }

        using (writer.Block($"namespace {Namespace}"))
        {
            WriteBody(writer);
        }

        return writer;
    }

    private void WriteBody(CodeWriter writer)
    {
        for (var i = 0; i < _builders.Count; i++)
        {
            _builders[i].Write(writer);
            if (i < _builders.Count - 1)
                writer.NewLine();
        }
    }

    public string Build() => BuildInternal().Render();

    public override string ToString() => Build();

    private static void WriteAssemblyAttributes(
        IReadOnlyList<string> assemblyAttributes,
        ref CodeWriter writer
    )
    {
        if (assemblyAttributes.Count == 0)
            return;

        var sortedAttrs = assemblyAttributes
            .Where(x => !string.IsNullOrEmpty(x))
            .Distinct()
            .OrderBy(x => x, StringComparer.Ordinal);

        foreach (var attr in sortedAttrs)
        {
            var output = attr;
            if (attr[0] != '[' || !attr.StartsWith("[assembly:", StringComparison.Ordinal))
            {
                output = $"[assembly: {attr}]";
            }

            output = output.Replace("[[", "[").Replace("]]", "]");
            writer.AppendLine(output);
        }
    }

    private static void WriteNamespaceGroup(List<string> namespaces, ref CodeWriter writer)
    {
        foreach (var import in namespaces)
            writer.AppendLine($"using {import};");
    }
}
